/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.c"
#include "init_clock.c"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void wait(volatile uint32_t count) {
  while (count--) {
    __asm__("nop");
  }
}

int main(void) {
  init_clock();

  // Enable clocks
  volatile uint32_t *RCC_AHB4ENR = (uint32_t *)0x580244E0;
  *RCC_AHB4ENR |= 0b1111111111; // Enable GPIOA to GPIOK clocks
 
  //do a funny
  *(volatile uint32_t *)0xCC000000 = 0xBEEF;
  uint32_t res = *(volatile uint32_t *)0xCC000000;
  if (res != 0xBEEF) {
      while (1); // Error
  }

  // PI13 = output (LED)
  set_output('I', 13);

  while (1) {
      write_pin('I', 13, read_pin('I', 13) ^ 1);
      wait(1000000);
  }
}
